name: Publish container image

on:
  push:
    branches: [main]
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  publish:
    uses: genebean/.github/.github/workflows/publish-container.yml@main
    with:
      image: ghcr.io/genebean/ytdlfin
